namespace ShmupWarz
(**
 * Entitas Generated Matcher Extensions for ShmupWarz
 *
 * do not edit this file
 *)
[<AutoOpen>]
module MatcherExtensions =

    open Entitas
    open System
    open System.Collections.Generic

    type Matcher with
        static member Bounds
            with get() = 
                Matcher.AllOf(Component.Bounds) 

        static member Bullet
            with get() = 
                Matcher.AllOf(Component.Bullet) 

        static member ColorAnimation
            with get() = 
                Matcher.AllOf(Component.ColorAnimation) 

        static member Enemy
            with get() = 
                Matcher.AllOf(Component.Enemy) 

        static member Expires
            with get() = 
                Matcher.AllOf(Component.Expires) 

        static member Firing
            with get() = 
                Matcher.AllOf(Component.Firing) 

        static member Health
            with get() = 
                Matcher.AllOf(Component.Health) 

        static member ParallaxStar
            with get() = 
                Matcher.AllOf(Component.ParallaxStar) 

        static member Player
            with get() = 
                Matcher.AllOf(Component.Player) 

        static member Position
            with get() = 
                Matcher.AllOf(Component.Position) 

        static member ScaleAnimation
            with get() = 
                Matcher.AllOf(Component.ScaleAnimation) 

        static member SoundEffect
            with get() = 
                Matcher.AllOf(Component.SoundEffect) 

        static member View
            with get() = 
                Matcher.AllOf(Component.View) 

        static member Velocity
            with get() = 
                Matcher.AllOf(Component.Velocity) 

        static member Score
            with get() = 
                Matcher.AllOf(Component.Score) 

        static member Destroy
            with get() = 
                Matcher.AllOf(Component.Destroy) 

        static member Mouse
            with get() = 
                Matcher.AllOf(Component.Mouse) 

        static member Scale
            with get() = 
                Matcher.AllOf(Component.Scale) 

        static member Resource
            with get() = 
                Matcher.AllOf(Component.Resource) 

        static member Layer
            with get() = 
                Matcher.AllOf(Component.Layer) 

        static member Background
            with get() = 
                Matcher.AllOf(Component.Background) 

        static member Mine
            with get() = 
                Matcher.AllOf(Component.Mine) 

        static member Status
            with get() = 
                Matcher.AllOf(Component.Status) 

        static member Life
            with get() = 
                Matcher.AllOf(Component.Life) 
