namespace ShmupWarz
(**
 * Entitas Global Functions for ShmupWarz
 *
 * do not edit this file
 *)

//module List =
//    let contains x = List.exists ((=) x)
// 
//module Array =
//    let contains x = Array.exists ((=) x)
// 
//module Seq =
//    let contains x = Seq.exists ((=) x)
    
[<AutoOpen>]
module GlobalFunctions =
    //let isNull x = match x with null -> true | _ -> false
    //let notNull x = match x with null -> false | _ -> true
    //let rnd = new System.Random()
    //let UNull x = (** Unity Version *)
    //    let y = box x // In case of value types
    //    obj.ReferenceEquals(y, Unchecked.defaultof<_>) || // Regular null check
    //    y.Equals(Unchecked.defaultof<_>) // Will call Unity overload if needed
    ()
